config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :movies do
    collection do
      get :search
    end
  end

  namespace :admin do
    root "static_pages#home"

    resources :users
    resources :movies
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    if user.administrator?
      can :manage, :all
    else
      can :read, :all
      can :update, User, id: user.id
      can :destroy, Comment, user_id: user.id
      can :destroy, MovieFollowing, user_id: user.id
      can :create, Comment
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :movies

  scope :key_value_pairs, ->{pluck :name, :id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  validates :content, presence: true,
    length: {maximum: Settings.comment.max_content}

  delegate :full_name, to: :user, allow_nil: true

  scope :recent, ->{order created_at: :desc}

  def owner? user
    user == self.user
  end
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  validates :word_en, :word_vi, :pronounciation, presence: true
  scope :key_value_pairs, ->{pluck :word_en, :id}
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :movie
  has_many :subtitles

  validates :name, :video_url, :movie_id, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, :movie_id, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
  has_and_belongs_to_many :movies

  scope :key_value_pairs, ->{pluck :name, :id}
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :movies
  scope :key_value_pairs, ->{pluck :name, :id}
end

app/models/movie.rb
class Movie < ApplicationRecord
  include Filterable
  belongs_to :category
  belongs_to :level
  has_and_belongs_to_many :genres
  has_many :favorites
  has_many :users, through: :favorites
  has_many :episodes
  has_and_belongs_to_many :dirictionaries
  has_and_belongs_to_many :users
  has_many :movie_followings, dependent: :destroy
  has_many :users, through: :movie_followings
  has_many :rating_movies, dependent: :destroy
  has_many :users, through: :rating_movies
  has_many :user_movies, dependent: :destroy
  has_many :users, through: :user_movies
  has_many :comments, dependent: :destroy

  scope :newest, ->{order created_at: :desc}
  scope :column_sort, ->(column){order "? DESC", column}
  scope :level, ->(level_id){where level_id: level_id}
  scope :genre, (lambda do |genre_id|
    joins(:genres).where("genres_movies.genre_id = ?", genre_id)
  end)
  scope :category, ->(category_id){where category_id: category_id}
  scope :features, ->{where is_feature: true}
  scope :term, (lambda do |term|
    where "title_en LIKE ? OR title_vi LIKE ?", "%#{term}%", "%#{term}%"
  end)

  def self.filterable_columns
    {is_feature: I18n.t("sort_column.feature"),
     views: I18n.t("sort_column.views"),
     created_at: I18n.t("sort_column.newest")}.map{|key, value| [value, key]}
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: User.name
  belongs_to :actor, class_name: User.name
  belongs_to :notifiable, polymorphic: true

  scope :unread, ->{where read_at: nil}
  scope :recent, ->(limit){order(created_at: :desc).limit limit}
  scope :get_notifiable, ->(id){where notifiable_id: id}
end

app/models/rating_movie.rb
class RatingMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, :movie_id, :rate, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/search.rb
class Search
  attr_accessor :movies, :levels, :categories, :genres, :sort_by
end

app/models/subtitle.rb
class Subtitle < ApplicationRecord
  belongs_to :episode
  has_and_belongs_to_many :users

  scope :load_subtitles, ->(episode_id){where episode_id: episode_id}
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  include Filterable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :async, :registerable, :confirmable,
    :recoverable, :rememberable, :validatable

  # Enum, Constants
  enum gender: {male: 0, female: 1}
  enum role: {member: 0, administrator: 1}

  attr_accessor :remember_token

  # Relationships
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :suggests
  has_many :favorited_movies, foreign_key: :user_id, class_name: Favorite.name,
    dependent: :destroy
  has_many :favoriting, through: :favorited_movies, source: :movie
  has_many :movie_followings, foreign_key: :user_id,
    class_name: MovieFollowing.name, dependent: :destroy
  has_many :followed_movies, through: :movie_followings, source: :movie
  has_many :rating_movies, dependent: :destroy, foreign_key: :user_id
  has_many :rated_movies, through: :rating_movies, source: :movie
  has_many :comments, dependent: :destroy
  has_many :user_movies, dependent: :destroy, foreign_key: :user_id
  has_many :watched_movies, through: :user_movies, source: :movie
  has_many :movie_vocabularies, foreign_key: :user_id,
    class_name: UserVocabulary.name, dependent: :destroy
  has_many :vocabularies, through: :movie_vocabularies, source: :dictionary
  has_many :notifications, foreign_key: :recipient_id

  # Validations
  validates :full_name, :date_of_birth, :gender, presence: true
  validates :full_name, length: {maximum: Settings.user.name.max_length}

  # Scopes
  scope :role, ->(role_id){where role: role_id}
  scope :gender, ->(gender_id){where gender: gender_id}
  scope :term, (lambda do |term|
    where "email LIKE ? OR full_name LIKE ?", "%#{term}%", "%#{term}%"
  end)

  # Follows a user.
  def follow other_user
    following << other_user
  end

  # Unfollows a user.
  def unfollow other_user
    following.delete other_user
  end

  def saved_vocabularies movie_id
    vocabularies.where "user_vocabularies.movie_id= ?", movie_id
  end

  def find_vocabulary movie_id, dictionary_id
    movie_vocabularies.find_by movie_id: movie_id, dictionary_id: dictionary_id
  end
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :movie_id, :user_id, presence: true
end

app/models/vocabulary.rb
class Vocabulary < ApplicationRecord
  belongs_to :dictionary
  belongs_to :movie
  validates :dictionary_id, :movie_id, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @feature_movies = Movie.features.newest.paginate(page: params[:page],
      per_page: Settings.home.movies)
    @levels = Level.includes :movies
    respond_to do |format|
      format.html
      format.json{render json: @feature_movies}
      format.js
    end
  end
end

app/helpers/date_helper.rb
module DateHelper
  def weekly
    (Date.today.at_beginning_of_week..Date.today.at_end_of_week).map
  end

  def month_begin
    Date.new Date.today.year, Date.today.month
  end
end

app/helpers/users_helper.rb
require "digest"
module UsersHelper
  def gravatar_for user, options = {size: Settings.gravatar.size.user}
    md5 = Digest::MD5.new
    gravatar_id = md5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.full_name, class: "gravatar")
  end

  def has_vocabularies? movie_id
    current_user.saved_vocabularies(movie_id).any?
  end

  def has_follow_movie? movie
    @following = current_user.movie_followings.find_by movie_id: movie.id
    @following ? t(:unfollow) : t(:follow)
  end

  def has_favorite_movie_text movie
    @favorite = current_user.favorited_movies.find_by movie_id: movie.id
    @favorite ? t("tooltip.favorite.remove") : t(:add_favorite)
  end

  def has_favorite_movie? movie
    current_user.favorited_movies.find_by movie_id: movie.id
  end
end

app/views/home/_feature.html.erb
<% (1..2).each do %>
  <div class="col-md-6">
    <div class="feature-item">
      <div class="icon">
        <i class="glyphicon glyphicon-book"></i>
        <%= t "feature.title" %>
      </div>
      <div class="feature-content">
        <%= t "feature.content" %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_feature_movie.html.erb
<div class="col-md-3 movie-item">
  <%= image_tag movie.image_url, class: "img-responsive" %>
  <%= link_to(movie_path(id: movie.id), class: "movie-title") do %>
    <%= summary movie.title_en, Settings.summary.title_en %>
  <% end %>
  <p class="movie-title">
    <%= summary movie.title_vi, Settings.summary.title_vi %>
  </p>
  <div class="extra-info">
    <p class="liked">
      <i class="glyphicon glyphicon-heart"></i>
      <%= t :favorite %>
    </p>
    <p class="float-right">
      <i class="glyphicon glyphicon-user"></i>
    </p>
  </div>
</div>
<%= will_paginate collection unless defined? not_paginate %>

app/views/home/_level.html.erb
<div class="row ml-0">
  <h3 class="section-header">
    <%= t("movies_in_level") << level.name %>
    <%= link_to t("view_all"), search_movies_path("q[level_id_eq]": level.id),
      class: "view-all" %>
  </h3>
  <%= render partial: "home/feature_movie",
    collection: level.movies.take(Settings.home.movies), as: :movie %>
</div>

app/views/home/_movie.html.erb
<% (1..5).each do |thing| %>
  <li class="item">
    <div class="image">
      <%= image_tag "/uploads/mv-1.jpg" %>
    </div>
    <div class="item-info">
      <h4><%= t "movie.title.en" %></h4>
      <p class="text-muted">
        <%= t "movie.title.vi" %>
      </p>
    </div>
  </li>
<% end %>

app/views/home/_slider.html.erb
<% (1..3).each do |i| %>
  <div class="item <%= i == 1 ? :active : "" %>">
    <%= image_tag "https://www.w3schools.com/bootstrap/la.jpg" %>
  <div class="header-text hidden-xs">
    <a href="#">
      <h3>
        <%= t "movie.title.en" %>
        <br>
        <small><%= t "movie.title.vi" %></small>
      </h3>
    </a>
    <p><%= t "movie.content" %></p>
    <button class="btn btn-default pull-right flat">
      <%= t :watch_movie %>
    </button>
  </div>
</div>
<% end %>

app/views/home/index.html.erb
<div class="full-screen">
  <div id="myCarousel" class="carousel movies-carousel slide"
    data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <%= render "home/slider" %>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only"><%=  t :previous %></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only"><%= t :next %></span>
    </a>
  </div>
</div>
<div class="feature surround-me-100">
  <div class="row">
    <%= render "home/feature" %>
  </div>
</div>

<div class="full-screen mt-30">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-9 movie-list">
        <div class="list-item">
          <h3 class="section-header"><%= t "feature_movies" %></h3>
          <div id="feature-movies">
            <%= render partial: "feature_movie",
              collection: @home.feature_movies,
              locals: {collection: @home.feature_movies}, as: :movie %>
          </div>
        </div>
        <%= render partial: "level",
          collection: @home.levels, as: :level %>
      </div>
      <div class="col-md-3 rightside">
        <h3 class="rightside-header">
          <%= t :movies_month %>
        </h3>
        <div class="aside-movies">
          <ul class="nav nav-tabs">
            <li class="active">
              <%= link_to t(:daily), "#daily", {"data-toggle": "tab"} %>
            </li>
            <li>
               <%= link_to t(:weekly), "#weekly", {"data-toggle": "tab"} %>
            </li>
            <li>
              <%= link_to t(:monthly), "#monthly", {"data-toggle": "tab"} %>
            </li>
          </ul>
          <div class="tab-content">
            <div id="daily" class="tab-pane fade in active">
              <ul class="movies">
                <%= render "home/movie" %>
              </ul>
            </div>
            <div id="weekly" class="tab-pane fade in">
              <ul class="movies">
                <%= render "home/movie" %>
              </ul>
            </div>
            <div id="monthly" class="tab-pane fade in">
              <ul class="movies">
                <%= render "home/movie" %>
              </ul>
            </div>
          </div>
        </div>
        <h3 class="rightside-header">
          <%= t :series_month %>
        </h3>
        <div class="aside-movies">
          <ul class="nav nav-tabs">
            <li class="active">
              <%= link_to t(:daily), "#serie-daily",
                {"data-toggle": "tab"} %>
            </li>
            <li>
               <%= link_to t(:weekly), "#serie-weekly",
                {"data-toggle": "tab"} %>
            </li>
            <li>
              <%= link_to t(:monthly), "#serie-monthly",
                {"data-toggle": "tab"} %>
            </li>
          </ul>
          <div class="tab-content">
            <div id="serie-daily" class="tab-pane fade in active">
              <ul class="movies">
                <%= render "home/movie" %>
              </ul>
            </div>
            <div id="serie-weekly" class="tab-pane fade in">
              <ul class="movies">
                <%= render "home/movie" %>
              </ul>
            </div>
            <div id="serie-monthly" class="tab-pane fade in">
              <ul class="movies">
                <%= render "home/movie" %>
              </ul>
            </div>
          </div>
        </div>
        <h3 class="rightside-header"><%= t :suggest_movie %></h3>
        <div class="aside-movies">
          <%= render "layouts/suggest_form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.js.erb
$('#feature-movies')
  .html('<%= j render(partial: "feature_movie",\
    collection: @home.feature_movies, as: :movie,\
    locals: {collection: @home.feature_movies}) %>');
$('.pagination a').attr('data-remote', 'true');