config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :movies do
    collection do
      get :search
    end
  end

  namespace :admin do
    root "static_pages#home"

    resources :users
    resources :movies
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Filterable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :async, :registerable, :confirmable,
    :recoverable, :rememberable, :validatable

  # Enum, Constants
  enum gender: {male: 0, female: 1}
  enum role: {member: 0, administrator: 1}

  attr_accessor :remember_token

  # Relationships
  has_many :active_relationships, class_name: Relationship.name,
    foreign_key: :follower_id, dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :suggests
  has_many :favorited_movies, foreign_key: :user_id, class_name: Favorite.name,
    dependent: :destroy
  has_many :favoriting, through: :favorited_movies, source: :movie
  has_many :movie_followings, foreign_key: :user_id,
    class_name: MovieFollowing.name, dependent: :destroy
  has_many :followed_movies, through: :movie_followings, source: :movie
  has_many :rating_movies, dependent: :destroy, foreign_key: :user_id
  has_many :rated_movies, through: :rating_movies, source: :movie
  has_many :comments, dependent: :destroy
  has_many :user_movies, dependent: :destroy, foreign_key: :user_id
  has_many :watched_movies, through: :user_movies, source: :movie
  has_many :movie_vocabularies, foreign_key: :user_id,
    class_name: UserVocabulary.name, dependent: :destroy
  has_many :vocabularies, through: :movie_vocabularies, source: :dictionary
  has_many :notifications, foreign_key: :recipient_id

  # Validations
  validates :full_name, :date_of_birth, :gender, presence: true
  validates :full_name, length: {maximum: Settings.user.name.max_length}

  # Scopes
  scope :role, ->(role_id){where role: role_id}
  scope :gender, ->(gender_id){where gender: gender_id}
  scope :term, (lambda do |term|
    where "email LIKE ? OR full_name LIKE ?", "%#{term}%", "%#{term}%"
  end)

  # Follows a user.
  def follow other_user
    following << other_user
  end

  # Unfollows a user.
  def unfollow other_user
    following.delete other_user
  end

  def saved_vocabularies movie_id
    vocabularies.where "user_vocabularies.movie_id= ?", movie_id
  end

  def find_vocabulary movie_id, dictionary_id
    movie_vocabularies.find_by movie_id: movie_id, dictionary_id: dictionary_id
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_options_pairs, only: :index

  def index
    search_params = params.slice :term, :role, :gender
    search_params[:gender] = correct_gender if params[:gender].present?
    @users = User.filter(search_params).paginate page: params[:page],
      per_page: Settings.home.users
    respond_to do |format|
      format.html
      format.js
    end
  end

  private
  def load_options_pairs
    @roles = User.roles
    @genders = User.genders
  end

  def correct_gender
    if params[:gender] == Settings.gender.male_text
      Settings.gender.male
    else
      Settings.gender.female
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :load_user, only: :show

  def show; end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "not_found.user"
    redirect_to page_404_path
  end
end

app/helpers/users_helper.rb
require "digest"
module UsersHelper
  def gravatar_for user, options = {size: Settings.gravatar.size.user}
    md5 = Digest::MD5.new
    gravatar_id = md5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.full_name, class: "gravatar")
  end

  def has_vocabularies? movie_id
    current_user.saved_vocabularies(movie_id).any?
  end

  def has_follow_movie? movie
    @following = current_user.movie_followings.find_by movie_id: movie.id
    @following ? t(:unfollow) : t(:follow)
  end

  def has_favorite_movie_text movie
    @favorite = current_user.favorited_movies.find_by movie_id: movie.id
    @favorite ? t("tooltip.favorite.remove") : t(:add_favorite)
  end

  def has_favorite_movie? movie
    current_user.favorited_movies.find_by movie_id: movie.id
  end
end

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.full_name %></td>
  <td><%= t "#{user.gender}" %></td>
  <td><%= user.email %></td>
  <td><%= l user.date_of_birth %></td>
  <td><%= t "#{user.role}" %></td>
  <td><%= l user.created_at %></td>
  <td><%= %></td>
</tr>

app/views/admin/users/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <!-- form search -->
          <%= form_tag admin_users_path, method: :get, enforce_utf8: false,
            class: "form-inline" do %>
            <h1>
              <%= t("admin.views.users.page_heading") %>
              <%= text_field_tag :term, params[:term], id: "search_users",
                class: "form-control" %>
              <%= submit_tag t("admin.submit.user.search"), name: nil,
                class: "btn btn-default" %>
            </h1>
          <% end %>
        </div>
        <!-- form filter -->
        <div class="well well-sm">
          <%= form_tag admin_users_path, method: :get, id: "filter",
            class: "form-inline", enforce_utf8: false, remote: true do %>
            <%= select_tag(:role,
              options_for_select(@roles),
              include_blank: t("admin.views.users.filter_role"),
              class: "btn btn-default") %>
            <%= select_tag(:gender,
              options_for_select(@genders),
              include_blank: t("admin.views.users.filter_gender"),
              class: "btn btn-default") %>
            <%= submit_tag t("admin.submit.user.filter"), name: nil,
              class: "btn btn-default" %>
            <%= hidden_field_tag :term, params[:term] %>
          <% end %>
        </div>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message,
            class: "alert alert-#{message_type}") %>
        <% end %>
        <!-- table users -->
        <% if @users.blank? %>
          <div class="alert alert-danger">
            <%= t("admin.views.users.not_found") %>
          </div>
        <% else %>
          <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
              <thead>
                <tr>
                  <th><%= t("admin.views.users.name") %></th>
                  <th><%= t("admin.views.users.gender") %></th>
                  <th><%= t("admin.views.users.email") %></th>
                  <th><%= t("admin.views.users.dob") %></th>
                  <th><%= t("admin.views.users.role") %></th>
                  <th><%= t("admin.views.users.join_date") %></th>
                  <th><%= t("admin.views.users.tool") %></th>
                </tr>
              </thead>
              <tbody id="users">
                <%= render @users %>
              </tbody>
            </table>
            <div id="users-paging" align="center">
              <%= will_paginate @users %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.js.erb
$('#users').html('<%= j render @users %>');
$('.pagination a').attr('data-remote', 'true');
$('#users-paging').html('<%= will_paginate @users %>')